spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  SECRET_KEY: secretkey